# Generated by Django 5.2.8 on 2026-01-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_urlmap_delete_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmap',
            name='clicks',
            field=models.IntegerField(default=0, help_text='How many times this short url being clicked?'),
        ),
    ]
