# Generated by Django 5.2.8 on 2026-01-24 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_urlmap_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmap',
            name='clicks',
        ),
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.urlmap')),
            ],
        ),
    ]
