# Generated by Django 5.2.8 on 2026-01-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_remove_urlmap_clicks_clicks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlMap',
            new_name='UrlMaps',
        ),
    ]
