# Generated by Django 6.0.1 on 2026-01-29 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_remove_urlmaps_user_link_click_delete_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='clicked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
