# Generated by Django 6.0.1 on 2026-01-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_click_clicked_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='click',
            options={'ordering': ['-clicked_at']},
        ),
    ]
